=head1 NAME

QuickClose - close tickets with one click

=head1 DESCRIPTION

If you have similar tickets again and again and you close them with the same text every time then
this module might be interesting to you. In these cases it is annoying to click on "close" in the
ticket zoom, wait for the "close" window, enter the text and submit it. Wouldn't it be great to
close the ticket with one click in the ticket zoom?

This module adds a new item in the admin area where you can define "QuickClose" texts and after
installation a new dropdown box is added in the ticket zoom. When you select one of the QuickClose
texts in this dropdown the ticket is closed and an article is added to the ticket.

In the admin area you can define the text for the article, the article type and the ticket state.
For the article types this module asks for the allowed article types for AgentTicketClose.

This module uses the standard OTRS mechanisms to close the ticket as an AJAX call to
AgentTicketClose is started.

=head1 AUTHOR AND LICENSE

This package was written by Renee Baecker E<lt>otrs@perl-services.deE<gt>.

The package is licensed unter AGPL. If you
did not receive this file, see L<http://www.gnu.org/licenses/agpl.txt>.

=head1 ACKNOWLEDGMENTS

=head2 Patrick Rauscher

Fix error when using QuickClose with pending state

=head2 Finkregh

fix encoding of German translation file

=head2 Torsten Thau (c.a.p.e IT)

OwnerID and PendingDiff should be set to 0 if no value is passed

=head2 Sebastian

Under some circumstances the ticket id wasn't detected correctly (happened with parent-child-tickets).

=cut

